searchSpaceFile: search_space.json
trialCommand: python MGKT.py hs gkt a0910 5  # NOTE: change "python3" to "python" if you are using Windows
trialGpuNumber: 0
trialConcurrency: 1
tuner:
  name: GridSearch
trainingService:
  platform: local
experimentWorkingDirectory: ./nni-experiments